package com.acrebuild.core

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

private fun asset(path: String): ByteArray =
    java.io.File("../generated/$path").readBytes()

/**
 * Slice-1 contract tests against the real converted packs (generated by
 * `tools/convert_slice1.py` from the decoded pack-3/pack-6 artifacts).
 * Semantics asserted here were mined from `b.java`/`i.java`/`k.java` —
 * see docs/gameplay-mining/state-animation-map.md.
 */
class ClipContractTest {

    private val clip0 by lazy { Clip.load(asset("clips/clip0/clip.acpk")) }
    private val clip7 by lazy { Clip.load(asset("clips/clip7/clip.acpk")) }
    private val tile11 by lazy { Clip.load(asset("level0/tileset-11/clip.acpk")) }

    @Test fun `clip0 decodes with mined shape`() {
        assertEquals(393, clip0.animCount())
        assertEquals(1544, clip0.frameModule.size)
        assertEquals(368, clip0.moduleW.size)
    }

    @Test fun `clip7 decodes with mined shape`() {
        assertEquals(201, clip7.animCount())
        assertEquals(942, clip7.frameModule.size)
        assertEquals(332, clip7.moduleW.size)
    }

    @Test fun `frame pool fields are coherent`() {
        // every anim's frame span stays inside the pool
        for (a in 0 until clip0.animCount()) {
            val end = clip0.animFrameStart[a] + clip0.animFrameCount[a]
            assertTrue(end <= clip0.frameModule.size, "anim $a overruns pool")
        }
    }

    @Test fun `module index high bits resolve`() {
        // av | ((i & 0xC0) << 2) — modules can exceed 255
        val m0 = clip0.frameModuleIndex(0, 0)
        assertTrue(m0 in 0 until 368)
    }

    @Test fun `rect query returns hitbox for anim 0`() {
        val out = IntArray(4)
        clip7.rect(0, 0, 0, 0, out)
        assertTrue(out[2] > 0 && out[3] > 0, "hitbox w/h should be positive")
    }

    @Test fun `rect query mirrors x on flag bit0`() {
        val a = IntArray(4); val b = IntArray(4)
        clip7.rect(0, 0, 0, 0, a)
        clip7.rect(0, 0, 0, 1, b)
        assertEquals(-a[0] - a[2], b[0])
        assertEquals(a[1], b[1])
    }

    @Test fun `tileset cells index the object space`() {
        assertEquals(119, tile11.objPlaceCount.size)
        // each tile object = one placement
        for (o in 0 until tile11.objPlaceCount.size) {
            assertTrue(tile11.objPlaceCount[o] >= 1, "tile object $o empty")
        }
    }
}

class EntityFsmTest {

    private val clip by lazy { Clip.load(asset("clips/clip7/clip.acpk")) }

    @Test fun `setAnim resets counters and records previous`() {
        val e = Entity(11, clip)
        e.setAnim(7)
        e.T = 3; e.U = 1
        e.setAnim(4)
        assertEquals(7, e.Q)
        assertEquals(4, e.S)
        assertEquals(0, e.T); assertEquals(0, e.U)
    }

    @Test fun `out of range setAnim is rejected`() {
        val e = Entity(11, clip)
        e.setAnim(7)
        e.setAnim(999)
        assertEquals(7, e.S)
    }

    @Test fun `advanceAnim wraps at end like s()`() {
        val e = Entity(11, clip)
        e.setAnim(2)               // single-frame anim
        e.advanceAnim()            // U=1 > dur? wraps via T overflow
        var guard = 0
        while (!e.animFinished() && guard++ < 1000) e.advanceAnim()
        // now at last frame/last tick; one more advance wraps to frame 0
        e.advanceAnim()
        assertEquals(0, e.T)
        assertEquals(0, e.U)
    }

    @Test fun `P bit6 blocks advance`() {
        val e = Entity(11, clip)
        e.setAnim(0)
        e.P = e.P or 64
        e.advanceAnim()
        assertEquals(0, e.U)
    }

    @Test fun `integrate applies vel and anchor resync`() {
        val e = Entity(11, clip)
        e.setPositionPx(100, 50)
        e.ag = 2560   // 10 px/tick
        e.integrate()
        assertEquals(110, e.ak)
        assertEquals(110 shl 8, e.N)
    }
}

class Level0WorldTest {

    private fun world(): Level0World {
        // mirror of the game's conversion of decoded assets
        val level = LevelPack.load(asset("level0/level0.aclv"))
        val clips = mapOf(
            0 to Clip.load(asset("clips/clip0/clip.acpk")),
            7 to Clip.load(asset("clips/clip7/clip.acpk")),
            10 to Clip.load(asset("level0/tileset-10/clip.acpk")),
            11 to Clip.load(asset("level0/tileset-11/clip.acpk")),
            12 to Clip.load(asset("level0/tileset-12/clip.acpk")),
        )
        return Level0World(level, clips, DeterministicRandom(1L))
    }

    @Test fun `level decodes pack-6 shape`() {
        val w = world()
        assertEquals(627, w.level.cols)
        assertEquals(55, w.level.rows)
        assertEquals(637, w.level.entities.size)
        assertEquals(4, w.level.layers.size)
    }

    @Test fun `player spawns from a type-0 or 25 record`() {
        val w = world()
        assertNotNull(w.level.playerSpawn(), "level 0 must carry a spawn record")
    }

    @Test fun `collision out of bounds is solid sentinel 20`() {
        val w = world()
        assertEquals(20, w.level.collisionCell(-1, 0))
        assertEquals(20, w.level.collisionCell(0, -1))
        assertEquals(20, w.level.collisionCell(0, 55))
    }

    @Test fun `NPC family entities spawn at record positions`() {
        val w = world()
        assertTrue(w.npcs.isNotEmpty(), "expected clip-7 family entities")
        for (n in w.npcs) {
            assertTrue(n.ak in 0..w.level.worldW)
            assertTrue(n.al in 0..w.level.worldH)
        }
    }

    @Test fun `player falls with gravity and lands on solid ground`() {
        val w = world()
        // settle: run ticks until landing or timeout
        var ticks = 0
        while (w.player.ah != 0 && ticks++ < 600) w.tick(emptyList())
        assertEquals(0, w.player.ah, "player should have landed")
        val feetCell = w.level.collisionCell(w.player.ak / 20, (w.player.al + 1) / 20)
        // feet cell may be one row below the anchor depending on hitbox;
        // assert the *supporting* cell is solid or one-way
        val v1 = w.level.collisionAtPx(w.player.ak, w.player.al + 1)
        val v2 = w.level.collisionAtPx(w.player.ak, w.player.al + 21)
        assertTrue(w.level.isSolid(v1) || w.level.isOneWay(v1) ||
                   w.level.isSolid(v2) || w.level.isOneWay(v2) ||
                   w.level.isSolid(feetCell),
            "player should rest on ground (got $v1/$v2/$feetCell)")
    }

    @Test fun `hold-right runs the player forward`() {
        val w = world()
        val x0 = w.player.ak
        val q = InputQueue()
        // middle-band right half -> held M_RIGHT (8256)
        q.post(InputQueue.Type.DOWN, 300, 120)
        repeat(30) { w.tick(q.drainTo(q.headSequence())) }
        assertTrue(w.player.ak > x0, "player should have moved right")
        // run cap ±2560 (proven literal from g.e()/ax())
        assertTrue(w.player.ag <= 2560)
    }

    @Test fun `player run uses clip0 anim 12 after run-start`() {
        val w = world()
        val q = InputQueue()
        q.post(InputQueue.Type.DOWN, 300, 120)
        // run-start (32) then sustained run (12)
        repeat(20) { w.tick(q.drainTo(q.headSequence())) }
        assertTrue(w.player.S == 12 || w.player.S == 32,
            "expected run anims 32/12, got ${w.player.S}")
    }

    @Test fun `tap top third jumps through 21-22-23-43-5 landing chain`() {
        val w = world()
        val q = InputQueue()
        // settle first
        repeat(10) { w.tick(emptyList()) }
        q.post(InputQueue.Type.DOWN, 200, 30)
        val seen = HashSet<Int>()
        repeat(60) {
            w.tick(q.drainTo(q.headSequence()))
            if (it == 1) q.post(InputQueue.Type.UP, 200, 30)
            seen += w.player.S
        }
        // jump chain: squat 21 -> rise 22/23 -> fall 43 -> land 5
        assertTrue(21 in seen || 22 in seen || 23 in seen,
            "expected jump anims, saw $seen")
        assertTrue(43 in seen || 5 in seen,
            "expected fall/land, saw $seen")
    }

    @Test fun `ax11 soldiers patrol off their home cell`() {
        val w = world()
        val soldiers = w.npcs.filter { it.ax == 11 }
        assertTrue(soldiers.isNotEmpty(), "expected ax11 records in level 0")
        val homes = soldiers.map { it.ak }
        repeat(120) { w.tick(emptyList()) }
        val moved = soldiers.zip(homes).count { (e, hx) -> kotlin.math.abs(e.ak - hx) > 8 }
        assertTrue(moved > 0, "no soldier patrolled: ${soldiers.map { it.S }}")
    }

    @Test fun `soldier alerts and chases when player enters the zone box`() {
        val w = world()
        // park the player inside a soldier's Z[9..12] alert box
        val s = w.npcs.firstOrNull { it.ax == 11 } ?: return
        repeat(5) { w.tick(emptyList()) }
        w.player.setPositionPx(s.Z[9] + 5, s.al)
        var alerted = false
        repeat(90) {
            w.tick(emptyList())
            if (s.aA != 0 || s.S == 5 || s.S == 4 || s.S == 23) alerted = true
        }
        assertTrue(alerted, "soldier should alert on player in zone (S=${s.S}, aA=${s.aA})")
    }

    @Test fun `alerted soldier strikes the player in melee range`() {
        val w = world()
        val s = w.npcs.firstOrNull { it.ax == 11 } ?: return
        repeat(5) { w.tick(emptyList()) }
        // stand the player next to the soldier inside its alert box
        w.player.setPositionPx(s.ak + 30, s.al)
        var struck = false
        repeat(200) {
            w.tick(emptyList())
            w.player.setPositionPx(s.ak + 30, s.al)   // keep in reach
            if (w.player.hitsTaken > 0 || w.player.S == 43) struck = true
        }
        assertTrue(struck,
            "soldier should land hits (S=${s.S}, hits=${w.player.hitsTaken})")
    }

    @Test fun `player vault attack damages and kills a soldier`() {
        val w = world()
        val s = w.npcs.firstOrNull { it.ax == 11 } ?: return
        repeat(5) { w.tick(emptyList()) }
        val hp0 = s.aB
        // pin player overlapping the soldier in an attack anim (67 sword combo)
        var sawDamage = false
        repeat(300) {
            w.player.setPositionPx(s.ak, s.al)
            if (w.player.S != 67) w.player.setAnim(67)
            w.tick(emptyList())
            if (s.aB < hp0) sawDamage = true
        }
        assertTrue(sawDamage, "player attacks should damage the soldier (aB=${s.aB})")
        // enough hits → aB<=0 → i(0) → i(139) corpse
        var corpse = false
        repeat(400) {
            w.player.setPositionPx(s.ak, s.al)
            if (s.aB > 0 && w.player.S != 67) w.player.setAnim(67)
            w.tick(emptyList())
            if (s.S == 139) corpse = true
        }
        assertTrue(s.aB <= 0 && corpse,
            "soldier should die to corpse S139 (aB=${s.aB}, S=${s.S})")
    }

    @Test fun `bottom-zone tap swings the sword and can kill a soldier`() {
        val w = world()
        val s = w.npcs.firstOrNull { it.ax == 11 } ?: return
        // walk the player to the soldier and tap attack (bottom-third zone)
        w.player.setPositionPx(s.ak - 20, s.al)
        w.tick(emptyList())
        var sawSlash = false; var kill = false
        repeat(600) {
            if (s.aB <= 0) { kill = true; return@repeat }
            w.player.setPositionPx(s.ak - 20, s.al)
            w.tick(listOf(InputQueue.Event(0, InputQueue.Type.DOWN, 200, 200),
                          InputQueue.Event(1, InputQueue.Type.UP, 200, 200)))
            if (w.player.S in intArrayOf(67, 68, 69, 112, 113, 114, 115, 81)) sawSlash = true
        }
        assertTrue(sawSlash, "tap should enter the sword combo (S=${w.player.S})")
        assertTrue(kill, "combo hits should kill the soldier (aB=${s.aB}, S=${s.S})")
    }

    @Test fun `assassination finisher kills a weakened locked soldier`() {
        val w = world()
        val s = w.npcs.firstOrNull { it.ax == 11 } ?: return
        repeat(5) { w.tick(emptyList()) }
        // aB=120 → one 80-dmg slash leaves 40 (<=H=50 → weakened via C()),
        // close enough for the X-arc to land the opening hit
        s.aB = 120
        w.player.setPositionPx(s.ak - 20, s.al)
        w.tick(emptyList())
        // lock claim + player mid-combo → tap → R=183|184 finisher
        w.player.setAnim(67)
        w.player.T = 0
        var sawFinisher = false
        for (i in 0 until 200) {
            if (s.S == 139 || (s.aB <= 0 && s.S == 0)) break
            if (w.player.S == 183 || w.player.S == 184) sawFinisher = true
            w.player.setPositionPx(s.ak - 20, s.al)
            w.tick(listOf(InputQueue.Event(0, InputQueue.Type.DOWN, 200, 200),
                          InputQueue.Event(1, InputQueue.Type.UP, 200, 200)))
        }
        assertTrue(sawFinisher, "weakened lock + tap → finisher anim")
        assertTrue(s.aB <= 0, "finisher should zero the victim (aB=${s.aB})")
    }

    @Test fun `npc strike on a metered player counters the attacker`() {
        val w = world()
        val s = w.npcs.firstOrNull { it.ax == 11 } ?: return
        // soldier mid-strike (S12 X-arc on frames 1-5), player grounded in it
        s.setAnim(12)
        var staggered = false
        for (i in 0 until 120) {
            w.player.setPositionPx(s.ak + (if (s.av) -20 else 20), s.al)
            w.player.ag = 0; w.player.ah = 0
            w.tick(emptyList())
            if (s.S == 9) { staggered = true; break }
        }
        assertTrue(staggered, "strike on metered player should counter → attacker S9")
        assertTrue(w.player.x1 < 90, "counter should pay meter u[0]=5 (x1=${w.player.x1})")
    }

    @Test fun `player knocked out at zero meter respawns at spawn`() {
        val w = world()
        val spawn = w.player.ak to w.player.al
        repeat(5) { w.tick(emptyList()) }
        w.player.setPositionPx(2000, 900)
        // knockdowns drain the meter via g.a() (u[0]=5): 90/5 = 18 ops;
        // reset g.t iframes between hits (each drain sets t=10)
        repeat(20) { w.player.applyHit(18, 0, null, w); w.player.gt = 0 }
        assertTrue(w.player.x1 <= 0, "meter should drain to 0 (x1=${w.player.x1})")
        w.tick(emptyList())
        assertEquals(90, w.player.x1, "respawn should refill the meter")
        assertEquals(spawn, w.player.ak to w.player.al, "player back at spawn")
        assertEquals(1, w.deaths)
    }

    @Test fun `iframes block a second drain for 10 ticks`() {
        val w = world()
        repeat(3) { w.tick(emptyList()) }
        w.player.applyHit(18, 0, null, w)
        assertEquals(85, w.player.x1)
        assertEquals(10, w.player.gt, "survived drain sets t=10")
        assertTrue(w.player.bh > 0, "hit flash set")
        // during iframes the op4->18 upgrade and drains are suppressed
        w.player.applyHit(18, 0, null, w)
        assertEquals(85, w.player.x1, "iframe blocks drain")
        repeat(9) { w.tick(emptyList()) }
        w.player.applyHit(18, 0, null, w)
        assertEquals(85, w.player.x1, "still iframe-protected on last tick")
        w.tick(emptyList())
        assertEquals(0, w.player.gt)
        w.player.setAnim(0)
        w.player.applyHit(18, 0, null, w)
        assertEquals(80, w.player.x1, "drains again after iframes expire")
    }

    @Test fun `op21 fall damage scales with drop distance`() {
        val w = world()
        w.player.gy = 400            // apex marker
        w.player.al = 400 + 20 * 20  // landed 20 cells lower
        w.player.applyHit(21, 0, w.player, w)
        assertEquals(0, w.player.x1, "20-cell fall: 105*(20)/20 = 105 dmg KO")
        val w2 = world()
        w2.player.gy = 400
        w2.player.al = 400 + 10 * 20 // 10-cell fall → 52 dmg
        w2.player.applyHit(21, 0, w2.player, w2)
        assertEquals(90 - 52, w2.player.x1)
    }
}
