package com.acrebuild.core

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

private fun asset(path: String): ByteArray =
    java.io.File("../generated/$path").readBytes()

/**
 * Slice-1 contract tests against the real converted packs (generated by
 * `tools/convert_slice1.py` from the decoded pack-3/pack-6 artifacts).
 * Semantics asserted here were mined from `b.java`/`i.java`/`k.java` —
 * see docs/gameplay-mining/state-animation-map.md.
 */
class ClipContractTest {

    private val clip0 by lazy { Clip.load(asset("clips/clip0/clip.acpk")) }
    private val clip7 by lazy { Clip.load(asset("clips/clip7/clip.acpk")) }
    private val tile11 by lazy { Clip.load(asset("level0/tileset-11/clip.acpk")) }

    @Test fun `clip0 decodes with mined shape`() {
        assertEquals(393, clip0.animCount())
        assertEquals(1544, clip0.frameModule.size)
        assertEquals(368, clip0.moduleW.size)
    }

    @Test fun `clip7 decodes with mined shape`() {
        assertEquals(201, clip7.animCount())
        assertEquals(942, clip7.frameModule.size)
        assertEquals(332, clip7.moduleW.size)
    }

    @Test fun `frame pool fields are coherent`() {
        // every anim's frame span stays inside the pool
        for (a in 0 until clip0.animCount()) {
            val end = clip0.animFrameStart[a] + clip0.animFrameCount[a]
            assertTrue(end <= clip0.frameModule.size, "anim $a overruns pool")
        }
    }

    @Test fun `module index high bits resolve`() {
        // av | ((i & 0xC0) << 2) — modules can exceed 255
        val m0 = clip0.frameModuleIndex(0, 0)
        assertTrue(m0 in 0 until 368)
    }

    @Test fun `rect query returns hitbox for anim 0`() {
        val out = IntArray(4)
        clip7.rect(0, 0, 0, 0, out)
        assertTrue(out[2] > 0 && out[3] > 0, "hitbox w/h should be positive")
    }

    @Test fun `rect query mirrors x on flag bit0`() {
        val a = IntArray(4); val b = IntArray(4)
        clip7.rect(0, 0, 0, 0, a)
        clip7.rect(0, 0, 0, 1, b)
        assertEquals(-a[0] - a[2], b[0])
        assertEquals(a[1], b[1])
    }

    @Test fun `tileset cells index the object space`() {
        assertEquals(119, tile11.objPlaceCount.size)
        // each tile object = one placement
        for (o in 0 until tile11.objPlaceCount.size) {
            assertTrue(tile11.objPlaceCount[o] >= 1, "tile object $o empty")
        }
    }
}

class EntityFsmTest {

    private val clip by lazy { Clip.load(asset("clips/clip7/clip.acpk")) }

    @Test fun `setAnim resets counters and records previous`() {
        val e = Entity(11, clip)
        e.setAnim(7)
        e.T = 3; e.U = 1
        e.setAnim(4)
        assertEquals(7, e.Q)
        assertEquals(4, e.S)
        assertEquals(0, e.T); assertEquals(0, e.U)
    }

    @Test fun `out of range setAnim is rejected`() {
        val e = Entity(11, clip)
        e.setAnim(7)
        e.setAnim(999)
        assertEquals(7, e.S)
    }

    @Test fun `advanceAnim wraps at end like s()`() {
        val e = Entity(11, clip)
        e.setAnim(2)               // single-frame anim
        e.advanceAnim()            // U=1 > dur? wraps via T overflow
        var guard = 0
        while (!e.animFinished() && guard++ < 1000) e.advanceAnim()
        // now at last frame/last tick; one more advance wraps to frame 0
        e.advanceAnim()
        assertEquals(0, e.T)
        assertEquals(0, e.U)
    }

    @Test fun `P bit6 blocks advance`() {
        val e = Entity(11, clip)
        e.setAnim(0)
        e.P = e.P or 64
        e.advanceAnim()
        assertEquals(0, e.U)
    }

    @Test fun `integrate applies vel and anchor resync`() {
        val e = Entity(11, clip)
        e.setPositionPx(100, 50)
        e.ag = 2560   // 10 px/tick
        e.integrate()
        assertEquals(110, e.ak)
        assertEquals(110 shl 8, e.N)
    }
}

class Level0WorldTest {

    private fun world(): Level0World {
        val level = LevelPack.load(asset("level0/level0.aclv"))
        val clips = mapOf(
            0 to Clip.load(asset("clips/clip0/clip.acpk")),
            7 to Clip.load(asset("clips/clip7/clip.acpk")),
            10 to Clip.load(asset("level0/tileset-10/clip.acpk")),
            11 to Clip.load(asset("level0/tileset-11/clip.acpk")),
            12 to Clip.load(asset("level0/tileset-12/clip.acpk")),
        )
        return Level0World(level, clips, DeterministicRandom(1L))
    }

    @Test fun `level decodes pack-6 shape`() {
        val w = world()
        assertEquals(627, w.level.cols)
        assertEquals(55, w.level.rows)
        assertEquals(637, w.level.entities.size)
        assertEquals(4, w.level.layers.size)
    }

    @Test fun `player spawns from a type-0 or 25 record`() {
        val w = world()
        assertNotNull(w.level.playerSpawn(), "level 0 must carry a spawn record")
    }

    @Test fun `collision out of bounds is solid sentinel 20`() {
        val w = world()
        assertEquals(20, w.level.collisionCell(-1, 0))
        assertEquals(20, w.level.collisionCell(0, -1))
        assertEquals(20, w.level.collisionCell(0, 55))
    }

    @Test fun `NPC family entities spawn at record positions`() {
        val w = world()
        assertTrue(w.npcs.isNotEmpty(), "expected clip-7 family entities")
        for (n in w.npcs) {
            assertTrue(n.ak in 0..w.level.worldW)
            assertTrue(n.al in 0..w.level.worldH)
        }
    }

    @Test fun `player falls with gravity and lands on solid ground`() {
        val w = world()
        // settle: run ticks until landing or timeout
        var ticks = 0
        while (w.player.ah != 0 && ticks++ < 600) w.tick(emptyList())
        assertEquals(0, w.player.ah, "player should have landed")
        val feetCell = w.level.collisionCell(w.player.ak / 20, (w.player.al + 1) / 20)
        // feet cell may be one row below the anchor depending on hitbox;
        // assert the *supporting* cell is solid or one-way
        val v1 = w.level.collisionAtPx(w.player.ak, w.player.al + 1)
        val v2 = w.level.collisionAtPx(w.player.ak, w.player.al + 21)
        assertTrue(w.level.isSolid(v1) || w.level.isOneWay(v1) ||
                   w.level.isSolid(v2) || w.level.isOneWay(v2) ||
                   w.level.isSolid(feetCell),
            "player should rest on ground (got $v1/$v2/$feetCell)")
    }

    @Test fun `hold-right runs the player forward`() {
        val w = world()
        val x0 = w.player.ak
        val q = InputQueue()
        q.post(InputQueue.Type.DOWN, 300, 200)
        repeat(30) { w.tick(q.drainTo(q.headSequence())) }
        assertTrue(w.player.ak > x0, "player should have moved right")
        assertTrue(w.player.ag <= Level0World.RUN_CAP)
    }
}
